# Generated by Django 3.1.1 on 2020-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_auto_20201104_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
